env:
  sources:
    - kind: deviceManager
      module: dodal.beamlines.i03
      mock: true
    - kind: planFunctions
      module: mx_bluesky.hyperion.blueapi.plans
  events:
    broadcast_status_events: true
api:
  url: http://localhost:5005
stomp:
  enabled: true
  url: tcp://localhost:61613
logging:
  level: DEBUG
