repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: ^uv.lock
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^helm/
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check --force-exclude --fix
        types: [python]
        require_serial: true

      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff format --force-exclude
        types: [python]
        require_serial: true
      
      - id: type-checking
        name: type-checking with pyright
        language: system
        entry: tox -e type-checking
        types: [python]
        require_serial: true

      - id: import-contracts
        name: Ensure import directionality
        pass_filenames: false
        language: system
        entry: lint-imports
        types: [python]
        require_serial: false

      - id: lock dodal
        name: keep dodal up to date in lockfile
        pass_filenames: false
        language: system
        entry: uv lock --upgrade-package dls-dodal

      - id: uv-sync
        name: update uv.lock and venv
        pass_filenames: false
        language: system
        entry: uv sync
        files: ^(uv\.lock|pyproject\.toml)$

      - id: local-install-dodal
        name: editable install of dodal
        language: system
        pass_filenames: false
        entry: uv pip install -e ../dodal
        files: ^(uv\.lock|pyproject\.toml)$

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        files: 'src/.*\.py$'
        additional_dependencies: [types-requests, types-redis, pydantic]
        args: ["--ignore-missing-imports", "--no-strict-optional"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
