# Configuration for the BlueAPI client running in the hyperion supervisor
# NOT TO BE USED IN PRODUCTION
api:
  url: http://localhost:5005
stomp:
  enabled: true
  url: tcp://localhost.diamond.ac.uk:61613
