on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true
      skip_hooks:
        description: "Comma-separated pre-commit hook IDs to skip"
        required: false
        type: string
        default: "" # important so the context always exists

jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run tox
        env:
          SKIP: ${{ inputs.skip_hooks }}
        run: uv run --locked tox -e ${{ inputs.tox }}
